### ISSUE TITLE
Please, support Arch Linux, Manjaro and Porteus!

### ISSUE THREAD

**Issue by gusbemacbe** [open-indy/Koa11y#18]
Hello,

I am an user of macOS, but I use mostly Manjaro (derived from Arch Linux) and Porteus (a Slackware-based) when I am out home.

**Comment by TheJaredWilcurt** [comment]
@gusbemacbe 
I'll make you a deal, if you can get [NW.js](http://nwjs.io) to run on either of those systems, then I will do builds for them in future releases.

All of the code-base is written using NW.js (specifically because it actually has decent Debian/Ubuntu/Zorin support). I don't know how to make it run on non-debian Linux versions, but if you can find a way I would like to know.

**Comment by gusbemacbe** [comment]
I am going to test now.

**Comment by gusbemacbe** [comment]
The app works perfectly on Manjaro, it ran quickly only in 2 and 4 seconds, but the file wasn't saved.

**Comment by gusbemacbe** [comment]
If it works perfectly on Manjaro, it also must work perfectly on Arch Linux.

**Comment by gusbemacbe** [comment]
I moved the folder and it was saved, but it is locked due to root. I have to run unrooted app.

**Comment by gusbemacbe** [comment]
I have just tested, it worked, but you have to write chmod 775 to run the unrooted app and save a unlocked file.

**Comment by TheJaredWilcurt** [comment]
@gusbemacbe 
So you're saying that Koa11y works on those platforms or NW.js does?

And which platform requires `chmod 775 Koa11y`, or do both of them?

**Comment by gusbemacbe** [comment]
@TheJaredWilcurt 

Only the `Koa11y.run`

The folder Koa11y needs to stay in the folder home for starting quickly without root and for not locking the file.

```
sudo chmod 775 Koa11y/Koa11y
./Koa11y
```

Before running it, Arch Linux, Manjaro and other Arch-based distros need to use AUR to install `npm `via octopi.

**Comment by gusbemacbe** [comment]
Good evening, @TheJaredWilcurt !

I have received the same errors:

```
(Koa11y:147604): Pango-ERROR **: 20:22:50.539: Harfbuzz version too old (1.2.1)
```

I have `canberra` installed. Harfbuzz's version is 2.7.4-1. I checked `pango` version:

```
ldd Koa11y | grep pango
        libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007f97d8b21000)
        libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007f97d89b0000)
        libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007f97d7e06000)
```

Compare to Arch's and Manjaro's `pango` versions:

```
ls /usr/lib/libpang*
/usr/lib/libpango-1.0.so                /usr/lib/libpangoft2-1.0.so           /usr/lib/libpangosharpglue-2.so
/usr/lib/libpango-1.0.so.0              /usr/lib/libpangoft2-1.0.so.0         /usr/lib/libpangoxft-1.0.so
/usr/lib/libpango-1.0.so.0.4800.2       /usr/lib/libpangoft2-1.0.so.0.4800.2  /usr/lib/libpangoxft-1.0.so.0
/usr/lib/libpangocairo-1.0.so           /usr/lib/libpangomm-1.4.so            /usr/lib/libpangoxft-1.0.so.0.4800.2
/usr/lib/libpangocairo-1.0.so.0         /usr/lib/libpangomm-1.4.so.1
/usr/lib/libpangocairo-1.0.so.0.4800.2  /usr/lib/libpangomm-1.4.so.1.0.30
```

Observe that packaing to the `build` folder, there was a small error:

```
Using v0.14.7 (normal)
Create cache folder in /home/gusbemacbe/GitHub/Outros/Koa11y/cache/0.14.7-normal
Using cache for: linux64
Create release folder in /home/gusbemacbe/GitHub/Outros/Koa11y/build/Koa11y/linux64
 ∙ NW-Builder Complete
 ∙ Copied package.json
 ∙ cd to build folder
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'Koa11y@4.0.0',
npm WARN EBADENGINE   required: { node: '5.12.0', npm: '3.8.6' },
npm WARN EBADENGINE   current: { node: 'v15.8.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 ∙ npm install build folder
 ∙ Started moving files into package.nw
  ∙ moved fonts
  ∙ moved img
  ∙ moved markup
  ∙ moved scripts
  ∙ moved style/style.css
nw-builder err Error: ENOENT: no such file or directory, link '/home/gusbemacbe/GitHub/Outros/Koa11y/build/Koa11y/linux64/style/ven.bootstrap.css' -> '/home/gusbemacbe/GitHub/Outros/Koa11y/build/Koa11y/linux64/package.nw/style/ven.bootstrap.css'
    at Object.linkSync (node:fs:1233:3)
    at tryRenameSync (/home/gusbemacbe/GitHub/Outros/Koa11y/node_modules/fs-extra/lib/move-sync/index.js:40:12)
    at Object.moveSync (/home/gusbemacbe/GitHub/Outros/Koa11y/node_modules/fs-extra/lib/move-sync/index.js:22:3)
    at /home/gusbemacbe/GitHub/Outros/Koa11y/build-script.js:187:16
    at Array.forEach (<anonymous>)
    at moveFilesIntoPackageNW (/home/gusbemacbe/GitHub/Outros/Koa11y/build-script.js:183:31)
    at /home/gusbemacbe/GitHub/Outros/Koa11y/build-script.js:303:9
    at updateExe (/home/gusbemacbe/GitHub/Outros/Koa11y/build-script.js:146:9)
```

ANother important observation is that `7zip-bin-linux` package is missed and should be aded to your `package.json`.

**Comment by gusbemacbe** [comment]
It turned that the problem was with `nw`'s old evrsion that supports only Pango 1.2. I upgraded `nw`'s 0.14 ro 05.2.0, Koa11 opens normally, but the elements disappeared:

![imagem](https://user-images.githubusercontent.com/2257024/110871254-cd94d100-82ac-11eb-8e08-47e67db9bc4b.png)
